version: '3.8'

name: shopper-app

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports: 
      - "4000:4000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: node
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend


  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    user: node
    restart: unless-stopped
    volumes:
      - ./admin:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - frontend
